apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices-demo
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  LOGGING__LOGLEVEL__DEFAULT: "Information"
  LOGGING__LOGLEVEL__MICROSOFT_ASPNETCORE: "Warning"
  # Internal Kubernetes cluster DNS addresses
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8081"
